.gitignore
PXWeb/Code/Views/ChartViewSerializer.cs

Custom chart title only works for the language that was selected when the saved query was created

---

PXWeb/Web.config

Upgraded ControlRenderingCompatibilityVersion to 4.5 to fix bug in the language manager tool

Upgraded ControlRenderingCompatibilityVersion to 4.5 

---

PXWeb/SavedQueryHandler.ashx.cs

Both PXModel and QueryModel must exist if cache shall be used. Otherwise reload the saved query.

Assert syncronized cache objects for saved queries

---

PCAxis.Api/packages.config
PCAxis.Excel.Web.Controls/packages.config
PXWeb/PXWeb.csproj
PXWeb/packages.config

FastMemebr was a dependency to ClosedXML but in the current version it is no longer used.

Removed references to FastMemeber since it is no longer used

---

CHANGES.txt
PCAxis.Web.Core/FileTypeMarkerControlBase.vb

Removed the extra byte that was allocated when downloading files.

Removed the extra byte

---

CHANGES.txt
PCAxis.Web.Controls/Menu/TableOfContent/TableOfContent.ascx
PXWeb/Menu.aspx.cs

Moved scroll script from treeview component. Injects it when needed when returning from selection page.
Scrolls to the last expanded node instead of the first one.

Fix for treeview scroll problem. Issue #187.

---

CHANGES.txt
PXWeb/PxWeb.Master
PXWeb/PxWeb.Master.cs
PXWeb/PxWeb.Master.designer.cs

Clicking the site logo will redirect you to the same URL as when clicking the home icon in the breadcrumb.

Made the site logo clickable. Issue 197.

---

CHANGES.txt
PCAxis.Web.Core/FileTypeMarkerControlBase.vb

When Downloading a file some clients might return Server sent to much data. This could be caused by the dynamic tags that are added in the master-pages
They can be disabled my setting the SupprestContent = true

Fixed error in downloading file

---

PCAxis.Charts/ChartHelper.cs
PCAxis.Charts/ChartSettings.cs
PXWeb/Admin/Features-Charts-General.aspx
PXWeb/Admin/Features-Charts-General.aspx.cs
PXWeb/Admin/Features-Charts-General.aspx.designer.cs
PXWeb/Code/Settings/ChartsSettings.cs
PXWeb/Code/Settings/Interfaces/IChartSettings.cs
PXWeb/Global.asax.cs
PXWeb/Resources/Languages/pxlang.sv.xml
PXWeb/Resources/Languages/pxlang.xml

* Background color of the graph has been added as a setting
* Alpha values for controlling the transparency of both background and chart background has been added as settings
It is now possible to control the transparency of graphs, resolves #183

Add the option of transparency in graph backgrounds

---

CHANGES.txt
PCAxis.Api/PCAxis.Api.csproj
PCAxis.Api/Serializers/JsonSerializer.cs
PCAxis.Api/Serializers/JsonStat2Seriaizer.cs
PCAxis.Api/Serializers/JsonStatSeriaizer.cs
PCAxis.Api/Serializers/SdmxDataSerializer.cs
PCAxis.Api/Serializers/XlsxSerializer.cs
PCAxis.Api/packages.config
PCAxis.Excel.Web.Controls/ExcelSerializerCreator.cs
PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
PCAxis.Excel.Web.Controls/SaveAsXlsx.cs
PCAxis.Excel.Web.Controls/packages.config
PCAxis.Html5Table.Web.Controls/Html5TableSerializerCreator.cs
PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
PCAxis.Html5Table.Web.Controls/SaveAsHtml5Table.cs
PCAxis.Html5Table.Web.Controls/packages.config
PCAxis.JsonStat.Web.Controls/JsonStatFileType.cs
PCAxis.JsonStat.Web.Controls/JsonStatSerializerCreator.cs
PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
PCAxis.JsonStat.Web.Controls/packages.config
PCAxis.JsonStat2.Web.Controls/JsonStat2FileType.cs
PCAxis.JsonStat2.Web.Controls/JsonStat2SerializerCreator.cs
PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
PCAxis.JsonStat2.Web.Controls/packages.config
PX.Json.Web.Controls/JsonSerializerCreator.cs
PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
PX.Json.Web.Controls/SaveAsJson.cs
PX.Json.Web.Controls/packages.config

Noticed a bit too late that https://github.com/statisticssweden/PxWeb/issues/163 said ".. All namespaces will be remain as they are to avoid extra work.". They are changed here.
(The buildToAzure breaks in build of PxWeb.Test, as it has TargetFramework netcoreapp3.1)

Switched from using 6 small Serializer nugets to one.

---

TemplateConfigFiles/Web.config

Removed no-store from the Cache-Control header to make the browser back-button work

Removed no-store from the Cache-Control header 

---

PXWeb/Admin/Tools-XMLGenerator.aspx.cs
PXWeb/Code/API/Controllers/DcatController.cs

The file created with the DataportalXML module is now saved in the folder of the corresponding database, located in the [databases](https://github.com/statisticssweden/PxWeb/tree/master/PXWeb/Resources/PX/Databases) folder. 
Using the DataportalXML tool on the Example database would result in a dcat-ap.xml file in [PXWeb/Resources/PX/Databases/Example](https://github.com/statisticssweden/PxWeb/tree/master/PXWeb/Resources/PX/Databases/Example)

Change save location of DCAT-AP XML file.

---

PXWeb/Controllers/Api2/Admin/CacheController.cs
PxWeb/Code/Api2/DataSource/Cnmm/ItemSelectionResolverCnmm.cs
PxWeb/Code/Api2/DataSource/PxFile/ItemSelectionResolverPxFile.cs
PxWeb/Code/Api2/DataSource/PxFile/TablePathResolverPxFile.cs

* Endpoint created under api/v2/admin/cache, a DELETE request will clear the IPxCache singleton
* Instances of IMemoryCache now use IPxCache instead
Builds on changes made in #267

Add endpoint for PxCache

---

PxWeb/Code/Api2/Cache/IPxCache.cs
PxWeb/Code/Api2/Cache/PxCache.cs
PxWeb/Config/Api2/CacheMiddlewareConfigurationOptions.cs
PxWeb/Config/Api2/CacheMiddlewareConfigurationService.cs
PxWeb/Config/Api2/ICacheMiddlewareConfigurationService.cs
PxWeb/Middleware/CacheMiddleware.cs
PxWeb/Program.cs
PxWeb/appsettings.json

* Cache middleware now has a separate variable for cache lifetime in appsettings.
* Cache middleware is not invoked for admin endpoints

Add separate cache time variable for middleware

---

PxWeb/Code/Api2/ModelBinder/QueryStringToDictionaryOfStrings.cs

Mad it possibleto have commas for GET requests. 
If the value code or selection expression contains a comma it should be surrounded by brackets like [TOP(1,12)].

Added escape mechanism for string splitting

---

CHANGES.txt
PXWeb/Admin/Tools-XMLGenerator.aspx
PXWeb/Admin/Tools-XMLGenerator.aspx.cs
PXWeb/Admin/Tools-XMLGenerator.aspx.designer.cs
PXWeb/Code/BackgroundWorker/PxWebBackgroundWorker.cs
PXWeb/Code/Settings/DatabaseSettings.cs
PXWeb/Code/Settings/DcatSettings.cs
PXWeb/Code/Settings/Enums/DcatStatusType.cs
PXWeb/Code/Settings/Interfaces/IDatabaseSettings.cs
PXWeb/Code/Settings/Interfaces/IDcatSettings.cs
PXWeb/Code/Settings/SettingsHelper.cs
PXWeb/PXWeb.csproj
PXWeb/Resources/Languages/pxlang.sv.xml
PXWeb/Resources/Languages/pxlang.xml
PXWeb/Resources/PX/Databases/Example/database.config

* Dcat tool can now be run as a background process by the BackgroundWorker
* Dcat settings are stored separately for each database in the corresponding database.config file
* The current status of creating the Dcat file is now shown on the interface

Dcat tool as background process

---

PCAxis.Web.Controls/Query/TableQuery.ascx
PCAxis.Web.Controls/Query/TableQuery.vb
PCAxis.Web.Controls/Query/TableQueryCodebehind.vb
PXWeb/Admin/Features-Api-General.aspx
PXWeb/Admin/Features-Api-General.aspx.cs
PXWeb/Admin/Features-Api-General.aspx.designer.cs
PXWeb/Code/Settings/ApiSettings.cs
PXWeb/Code/Settings/Interfaces/IApiSettings.cs
PXWeb/Presentation.master.cs
PXWeb/Resources/Languages/pxlang.sv.xml
PXWeb/Resources/Languages/pxlang.xml
PXWeb/Resources/PX/Databases/Example/Menu.xml
PXWeb/Resources/Styles/main-pxweb.css
PXWeb/Resources/Styles/scss/pxweb/_tablequery.scss

Links to api-v2 endpoints can now be enabled in settings, these work alongside Api 1.0 links with POST data.
fix #471

Api-V2 url links

---

PCAxis.Web.Controls/VariableSelector/VariableSelectorValueSelectCodebehind.vb

Fix for when you try to restore variable values by selecting "-- Select classification --" and there is no _ALL_ valueset

Fix for restore variables and there is no _ALL_ valueset

---

CHANGES.txt
PXWeb/Presentation.master.cs

See issue #624.
This tries to make sure that the  paxiom from PaxiomManager.PaxiomModel  is made for the same table as the url requests.
If it does a redirect when it should not, the user will be stuck in the selection-page, so we have to be sure...

Now redirects to selection-page if paxiom and url dont match

---

PXWeb/Code/API/Controllers/MenuController.cs

CodeQL complains about Uncontrolled data in the admin-api, but if the admin-api is turned on, it is behind password.
So the Abusecase it far-fetched, but it looks better without the alert if somebody forks and run codeQL.

stops a CodeQL complaint, for vanity reasons mostly

---

PCAxis.Web.Controls/VariableSelector/VariableSelectorCodebehind.vb

Change the if to make sure that a Content variable exists before using it.
Where getting NullRefrence exception.

Fix for NullRefrenceException when removing single contents.
