statisticssweden/PxWeb

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PCAxis.Common/PCAxis.Common.vbproj
- PCAxis.Common/packages.config
- PCAxis.Core/PCAxis.Core.vbproj
- PCAxis.Core/packages.config
- PCAxis.Menu/Menu/PCAxis.Menu.csproj
- PCAxis.Menu/Menu/packages.config
- PCAxis.PX.Core/PCAxis.PX.Core.vbproj
- PCAxis.PX.Core/packages.config
- PCAxis.Serializers.JsonStat/JsonStatSerializer/PCAxis.Serializers.JsonStat.csproj
- PCAxis.Serializers.JsonStat/JsonStatSerializer/packages.config
- PCAxis.Serializers.JsonStat2/JsonStat2Serializer/JsonStat2Serializer/PCAxis.Serializers.JsonStat2Serializer.csproj
- PCAxis.Serializers.JsonStat2/JsonStat2Serializer/JsonStat2Serializer/packages.config
- PCAxis.Sql.DbConfig/PCAxis.Sql.DbConfig.csproj
- PCAxis.Sql/PCAxis.Sql.csproj
- PCAxis.Sql/packages.config
- PCAxis.Web.Controls/PCAxis.Web.Controls.vbproj
- PCAxis.Web.Controls/packages.config
- PCAxis.Web.Core/PCAxis.Web.Core.vbproj
- PCAxis.Web.Core/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/packages.config
Upgraded to log4net 2.0.8 and added them as nuget references
> Upgraded log4net and added the refrences from nuget

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/packages.config
Added reference from nuget.org
> Added from nuget

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PCAxis.Charting/PxChart/PCAxis.Charting.csproj
- PCAxis.Charting/PxChart/packages.config
- PCAxis.Charts/PCAxis.Chart.csproj
- PCAxis.Charts/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/packages.config
- PCAxis.Menu/ConfigDatamodelMenu/PCAxis.Menu.Implementations.ConfigDatamodelMenu.csproj
- PCAxis.Menu/ConfigDatamodelMenu/packages.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/packages.config
- PCAxis.Web.Controls/PCAxis.Web.Controls.vbproj
- PCAxis.Web.Controls/packages.config
- PCAxis.Web.Core/PCAxis.Web.Core.vbproj
- PCAxis.Web.Core/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/packages.config
Added beta2 for PCAxis.Query and beta3 for PCAxis.PX.Core 
Udated to beta5 for PCAxis.Core and PCAxis.Common in projects that had beta4
> Added beta2 for PCAxis.Query and beta3 for PCAxis.PX.Core etc

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/app.config
- PCAxis.Api/packages.config
- PCAxis.Charting/PxChart/PCAxis.Charting.csproj
- PCAxis.Charting/PxChart/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/packages.config
- PCAxis.Menu/ConfigDatamodelMenu/PCAxis.Menu.Implementations.ConfigDatamodelMenu.csproj
- PCAxis.Menu/ConfigDatamodelMenu/app.config
- PCAxis.Menu/ConfigDatamodelMenu/packages.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/Web.config
- PXWeb/packages.config
PCAxis.PxExtend, PXWeb.SavedQuery.MsSql…PXWeb.SavedQuery.Oracle, PCAxis.Menu.MsSqlDatamodelMenu, PCAxis.Html5Table, PCAxis.Sdmx, PCAxis.Excel, PCAxis.Encryption, PCAxis.Metadata
> Updated nuget references to new betas 

- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PXWeb/PXWeb.csproj
- PXWeb/packages.config
Added AfterBuild instructions to copy the dll:s for the file serializers and web components to PxWeb project (Excel, Html5Table, JsonStat, JsonStat2 and Json)
> Added AfterBuild instructions for custom file format projetcs

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/packages.config
> Updated nuget for PCAxis.Excel

- PXWeb/PXWeb.csproj
- PXWeb/Resources/Languages/pxlang.en.xml
Added an english language file that can be edited in the Language manager tool.
> Added an english language file

- PXWeb/Code/Views/FileChartViewSerializer.cs
Added a check if the format is ColumnLine so that the IsColumnLine attribute can be set to fix bug #69
> Fix for bug #69 ColumnLine

- PXWeb/Default.aspx
- PXWeb/Default.aspx.designer.cs
- PXWeb/Menu.aspx
- PXWeb/Menu.aspx.designer.cs
- PXWeb/Search.aspx
- PXWeb/Search.aspx.designer.cs
Fixt problem with skiplink not working.
> Fix for skiplink issue. Iissue#76

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PCAxis.Charting/PxChart/PCAxis.Charting.csproj
- PCAxis.Charting/PxChart/packages.config
- PCAxis.Charts/PCAxis.Chart.csproj
- PCAxis.Charts/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/packages.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/packages.config
- PCAxis.Web.Controls/PCAxis.Web.Controls.vbproj
- PCAxis.Web.Controls/packages.config
- PCAxis.Web.Core/PCAxis.Web.Core.vbproj
- PCAxis.Web.Core/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/Web.config
- PXWeb/packages.config
Updated to newer version av the nuget packages
> Bumped up assembly version

- PCAxis.Api/SSDHandler.cs
> #135 Added error handler for SendJSONError in SSDHandler.cs

- PCAxis.Api/ApiCache.cs
> #139 Added logging improvement for metode Clear() in PCAxis.Api\ApiCache

- PCAxis.Search/Indexer.cs
> #137 Added error handler for metode UpdateIndex in PCAxis.Search\Indexer

- PXWeb/Resources/Languages/pxlang.sv.xml
Added some translation to Swedish for the new texts
> Translations for Swedish

- PXWeb/Resources/Languages/pxlang.sv.xml
Changed the square bracket to curly brackets
> Fixed sort view

- CHANGES.txt
Added CHANGES.txt that should be updated in branches that that should be merged to master
> Added CHANGES.txt

- PXWeb/Resources/PX/Aggregations/Readme.txt
So we dont have to create it when checking out ...
> Added a simple readme.txt to force git to create the Aggregations folder

- PxWeb/Program.cs
- PxWeb/PxWeb.csproj
- PxWeb/app.config
- PxWeb/log4net.config
Added log4net as the logging framework to the PxWeb project so that underlying will continue to work.
> Added log4net as logging framework

- CSSFriendly/CSSFriendly.csproj
- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/app.config
- PCAxis.Charting/PxChart/PCAxis.Charting.csproj
- PCAxis.Charts/PCAxis.Chart.csproj
- PCAxis.Charts/app.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/app.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/app.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/app.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/app.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/app.config
- PCAxis.Web.Controls/Extensions/PxWebControlExtensions.vb
- PCAxis.Web.Controls/My Project/Resources.Designer.vb
- PCAxis.Web.Controls/My Project/Settings.Designer.vb
- PCAxis.Web.Controls/PCAxis.Web.Controls.vbproj
- PCAxis.Web.Controls/app.config
- PCAxis.Web.Core/My Project/Resources.Designer.vb
- PCAxis.Web.Core/My Project/Settings.Designer.vb
- PCAxis.Web.Core/PCAxis.Web.Core.vbproj
- PCAxis.Web.Core/app.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/app.config
- PX.Security/PX.Security.csproj
- PX.Web.Interfaces/PX.Web.Interfaces.csproj
- PXWeb/PXWeb.csproj
> Upgraded Framwork to 4.8

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/packages.config
> Upgraded to the latest release of PCAxis.Serializers (Displays the entire footnote in Excel.)

- Px.Abstractions/Interfaces/IDataSource.cs
- Px.Abstractions/Px.Abstractions.csproj
- Px.Search.Lucene/LuceneBackend.cs
- Px.Search.Lucene/LuceneIndex.cs
- Px.Search.Lucene/LuceneSearcher.cs
- Px.Search.Lucene/Px.Search.Lucene.csproj
- Px.Search/IIndex.cs
- Px.Search/ISearchBackend.cs
- Px.Search/ISearcher.cs
- Px.Search/Indexer.cs
- Px.Search/Px.Search.csproj
- Px.Search/SearchResult.cs
- PxWeb.sln
- PxWeb/PxWeb.csproj
This contains the first implementation of Px.Search for adding search capability to the API.
> Adding search capability to PxAPI

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/app.config
- PCAxis.Api/packages.config
- PCAxis.Charting/PxChart/PCAxis.Charting.csproj
- PCAxis.Charting/PxChart/packages.config
- PCAxis.Charts/PCAxis.Chart.csproj
- PCAxis.Charts/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/app.config
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/packages.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/app.config
- PCAxis.Search/packages.config
- PCAxis.Web.Controls/PCAxis.Web.Controls.vbproj
- PCAxis.Web.Controls/packages.config
- PCAxis.Web.Core/PCAxis.Web.Core.vbproj
- PCAxis.Web.Core/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/packages.config
Updated nugets for PcAxis.Serializers and PcAxis.Core. To show presentation format in JsonStat and JsonStat2
> Updated serializer

- TemplateConfigFiles/Web.config
Compilation debug set to false and targetframwork to 4.8
> Compilation debug set to false and targetframwork to 4.8

- TemplateConfigFiles/Web.config
Empty APIKey added in template web.config
> Empty APIKey added in template web.config

- CHANGES.txt
- TemplateConfigFiles/Web.config
Updated template web.config with new assembly reference and new version number
> Updated template web.config

- Px.Search.Lucene/LuceneIndex.cs
Searchindex POST endpoint will overwrite existing index.
Searchindex PATCH endpoint will append existing index.
> Overwrite or append Lucene index

- PxWeb/appsettings.Release.json
misst a curly bracket in the appsettings.release
> misst a curly bracket in the appsettings key AdminProtection

- PxWeb/PxWeb.csproj
Upgraded to new version of PCAxis.Sql that contains the latest version of Microsoft.Data.SqlClient
> Added refrence to PCAxis.Sql 1.2.0

- PxWeb/PxWeb.csproj
Upgrede nuget AspNetCoreRateLimit and Newtonsoft.Json
> Upgrede nuget

- PxWeb/Controllers/Api2/NavigationApiController.cs
- PxWeb/Controllers/Api2/TableApiController.cs
- PxWeb/app.Release.config
- PxWeb/appsettings.Release.json
English as default language, variable for BaseUrl in relase configuation
> Changes in release configuration

- PxWeb/Config/Api2/CacheMiddlewareConfigurationOptions.cs
- PxWeb/Middleware/CacheMiddleware.cs
- PxWeb/appsettings.json
Added buffering to request to solve the problem in the cache middelware that reads the body.
> Added buffering to request

- PxWeb/Code/Api2/ModelBinder/QueryStringToDictionaryOfStrings.cs
- PxWeb/Controllers/Api2/TableApiController.cs
Added ModelBinder for types of dictionary where the key is a string and the value is a list of strings
> Added model binder for the data GET endpoint

- PxWeb/Code/Api2/Serialization/PxDataSerializer.cs
Added header with suggested file name in px-file Serializer
> Added header with suggested file name in px-file Serializer

- PCAxis.Web.Controls/CommandBar/CommandBarCodebehind.vb
> Fix split time error

- PXWeb/Selection.aspx.cs
> Fix compact view not being shown at first load

- PXWeb/Code/BackgroundWorker/ControllerState.cs
- PXWeb/Code/BackgroundWorker/ControllerStateProvider.cs
- PXWeb/Code/BackgroundWorker/IControllerState.cs
- PxWeb/Code/BackgroundWorker/ControllerStateData.cs
- PxWeb/Controllers/Api2/Admin/DatabaseController.cs
- PxWeb/Controllers/Api2/Admin/SearchindexController.cs
- PxWeb/wwwroot/Database/Menu.xml
Moved the ControllerState data into a separate class ControllerStateData since deserialization faild due to ControllerState missing a constructor without parameters. 
Since id a filepath where requeried for the ControllerState work as expected we mode the data that should be presisted to a separate class.
> Fix for GET call on DatabaseController and SearchIndexController

- PxWeb/Mappers/TableMetadataResponseMapper.cs
Get contact information from table level if it could not be read from content variable
> Get contact information from table level 

- PXWeb/Admin/Tools-XMLGenerator.aspx
- PXWeb/Admin/Tools-XMLGenerator.aspx.cs
- PXWeb/Admin/Tools-XMLGenerator.aspx.designer.cs
- PXWeb/Code/API/Controllers/DcatController.cs
- PXWeb/Code/BackgroundWorker/PxWebBackgroundWorker.cs
- PXWeb/Code/Settings/DcatLanguageSpecificSettings.cs
- PXWeb/Code/Settings/DcatSettings.cs
- PXWeb/Code/Settings/Interfaces/IDcatLanguageSpecificSettings.cs
- PXWeb/Code/Settings/Interfaces/IDcatSettings.cs
- PXWeb/Code/Settings/Settings.cs
- PXWeb/PXWeb.csproj
- PXWeb/Resources/PX/Databases/Example/Organizations.json
- PXWeb/Resources/PX/Databases/Example/database.config
- PXWeb/packages.config
* Publisher can now be set for different languages
> Language specific DCAT publisher names

- PXWeb/PXWeb.csproj
- PXWeb/packages.config
Updated Px.Dcat version to 2.0.5
> Updated Px.Dcat version to 2.0.5

- CHANGES.txt
- PCAxis.Web.Controls/Query/TableQueryCodebehind.vb
- PCAxis.Web.Controls/VariableSelector/VariableSelectorCodebehind.vb
- PCAxis.Web.Core/Management/PaxiomManager.vb
Updated TableQueryCodebehind to append query parameter based on SelectionContent. Enhanced VariableSelectorCodebehind to set SelectionContent conditionally.
> Add SelectionContent handling in TableQuery and VariableSelector for api2 querystring to generate properly 

- PCAxis.Api/PCAxis.Api.csproj
- PCAxis.Api/app.config
- PCAxis.Api/packages.config
- PCAxis.Excel.Web.Controls/PCAxis.Excel.Web.Controls.csproj
- PCAxis.Excel.Web.Controls/app.config
- PCAxis.Excel.Web.Controls/packages.config
- PCAxis.Html5Table.Web.Controls/PCAxis.Html5Table.Web.Controls.csproj
- PCAxis.Html5Table.Web.Controls/app.config
- PCAxis.Html5Table.Web.Controls/packages.config
- PCAxis.JsonStat.Web.Controls/PCAxis.JsonStat.Web.Controls.csproj
- PCAxis.JsonStat.Web.Controls/app.config
- PCAxis.JsonStat.Web.Controls/packages.config
- PCAxis.JsonStat2.Web.Controls/PCAxis.JsonStat2.Web.Controls.csproj
- PCAxis.JsonStat2.Web.Controls/app.config
- PCAxis.JsonStat2.Web.Controls/packages.config
- PCAxis.Search/PCAxis.Search.csproj
- PCAxis.Search/app.config
- PCAxis.Search/packages.config
- PX.Json.Web.Controls/PX.Json.Web.Controls.csproj
- PX.Json.Web.Controls/app.config
- PX.Json.Web.Controls/packages.config
- PXWeb/PXWeb.csproj
- PXWeb/packages.config
- TemplateConfigFiles/Web.config
Updated `System.IO.Packaging` and `System.Text.Json`
> Updated nuget packages

- PXWeb/Admin/Web.config
> removed small PXWeb/Admin/Web.config

- CHANGES.txt
- PXWeb/UserControls/SaveQueryCreate.ascx.cs
> Fix URL port handling for saved query

- PCAxis.Web.Controls/Query/TableQueryCodebehind.vb
Encode certain values when generating querystring for apiv2
> Encode certain values when generating querystring for apiv2

- CHANGES.txt
- PXWeb/Properties/AssemblyInfo.cs
Changed version number for new release
> Changed version number for new release

- PCAxis.Web.Controls/Query/TableQueryCodebehind.vb
- PCAxis.Web.Controls/VariableSelector/VariableSelectorCodebehind.vb
- PCAxis.Web.Core/Management/PaxiomManager.vb
Fixed a typographical error in PaxiomManager comments.
> Improve null checks and content selection handling.

- CHANGES.txt
- TemplateConfigFiles/Web.config
Updated assembly binding versions in template web.config
Moved order of lines and added new row in Changes.txt
> Updated assembly binding versions in template web.config
